[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fuzzywuzzy>=0.18.0",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "python-levenshtein>=0.27.1",
    "requests>=2.32.4",
    "streamlit>=1.46.1",
]
